openapi: 3.0.1
info:
  title: AgencyAPI
  version: 1.0.0
servers:
 -
  url: /
security:
 -
  default: []
paths:
  /customer-onboarding:
    post:
      parameters: []
      responses:
        "200":
          description: ok
      security:
       -
        default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - basic_auth
        optional: false
  /account-opening:
    post:
      parameters: []
      responses:
        "200":
          description: ok
      security:
       -
        default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - basic_auth
        optional: false
  /deposit:
    post:
      parameters: []
      responses:
        "200":
          description: ok
      security:
       -
        default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - basic_auth
        optional: false
  /withdraw:
    post:
      parameters: []
      responses:
        "200":
          description: ok
      security:
       -
        default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - basic_auth
        optional: false
components:
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: ""
          scopes: {}
x-wso2-auth-header: Authorization
x-throttling-tier: Unlimited
x-wso2-cors:
  corsConfigurationEnabled: false
  accessControlAllowOrigins:
   - '*'
  accessControlAllowCredentials: false
  accessControlAllowHeaders:
   - authorization
   - Access-Control-Allow-Origin
   - Content-Type
   - SOAPAction
   - apikey
   - testKey
  accessControlAllowMethods:
   - GET
   - PUT
   - POST
   - DELETE
   - PATCH
   - OPTIONS
x-wso2-production-endpoints:
  urls:
   - http://ei.dev.bracbank.local/agency-banking-api/v1
  type: http
x-wso2-sandbox-endpoints:
  urls:
   - http://ei.dev.bracbank.local/agency-banking-api/v1
  type: http
x-wso2-basePath: /agencyapi/1.0.0
x-wso2-transports:
 - http
 - https
x-wso2-response-cache:
  enabled: false
  cacheTimeoutInSeconds: 300
